### ISSUE TITLE
Node-Red hangs at exit after receiving messages with rdkafka consumer

### ISSUE THREAD

**Issue by hjespers** [hjespers/node-red-contrib-rdkafka#1]
This is related to a issue in the dependent package node-rdkafka ( see https://github.com/Blizzard/node-rdkafka/issues/5 ).

Have to kill node-red ungracefully to clear the condition.

**Comment by webmakersteve** [comment]
There is an upcoming refactor that should fix this issue. It results from the `RdKafka::Message*` underlying the returned `node::Buffer` waiting for the buffer to be garbage collected so it can successfully close the client.

The change should copy the memory instead of reference it so that the buffer no longer affects the shut down of the library.

**Comment by hjespers** [comment]
fixed in node-rdkafka (many thanks) and so now closed in node-red-contrib-rdkafka. Consumers not properly disconnect upon exit.
